config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/prinzio'
  get 'demo/escape_output'
  # match 'demo/index', :to => 'demo#index', :via => :get

  # get ':controller(/:action/(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  has_and_belongs_to_many :pages
  has_many :section_edits
  has_many :sections, :through => :section_edits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :subject
  has_and_belongs_to_many :admin_users
  scope :visible, -> { where(:visible => true) }
  scope :invisible, -> { where(:visible => false) }
  scope :sorted, -> { order('position ASC') }
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :section_edits
  has_many :admin_users, :through => :section_edits
  scope :visible, -> { where(:visible => true) }
  scope :invisible, -> { where(:visible => false) }
  scope :sorted, -> { order('position ASC') }
end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord
  belongs_to :admin_user
  belongs_to :section
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :pages
  scope :visible, -> { where(:visible => true) }
  scope :invisible, -> { where(:visible => false) }
  scope :sorted, -> { order('position ASC') }
  scope :newest_first, -> { order('created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout = 'application'

  def index
    render('index')
  end

  def hello
    @array = [1, 2, 3, 4, 5]
    @id = params[:id]
    @page = params[:page]
    render('hello')
  end

  def other_hello
    redirect_to(:action => 'index')
  end

  def prinzio
    redirect_to('http://prinzio.com')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout 'admin'

  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      flash[:notice] = 'Page created successfully.'
      redirect_to(pages_path)
    else
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if @page.update_attributes(page_params)
      flash[:notice] = 'Page updated successfully.'
      redirect_to(page_path(@page))
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Page '#{@page.name}' deleted successfully."
    redirect_to(pages_path)
  end

  private

  def page_params
    params.require(:page).permit(:subject_id, :name, :permalink, :position, :visible)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  layout 'admin'

  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      flash[:notice] = 'Section created succesfully.'
      redirect_to(sections_path)
    else
      render('new')
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])

    if @section.update_attributes(section_params)
      flash[:notice] = 'Section updated succesfully.'
      redirect_to(section_path(@section))
    else
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section #{@section.name} deleted succesfully."
    redirect_to(sections_path)
  end

  private

  def section_params
    params.require(:section).permit(:name, :page_id, :content, :content_type, :visible, :position)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout 'admin'

  def index
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new({:name => 'Default'})
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:notice] = 'Subject successfully created.'
      redirect_to(subjects_path)
    else
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update_attributes(subject_params)
      flash[:notice] = 'Subject successfully updated.'
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.name}' successfully deleted."
    redirect_to(subjects_path)
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :position, :visible)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper

  def status_tag(boolean, options={})
    options[:true_text] ||= ''
    options[:false_text] ||= ''

    if boolean
      content_tag(:span, options[:true_text], :class => 'status true')
    else
      content_tag(:span, options[:false_text], :class => 'status false')
    end
  end

end

app/views/demo/escape_output.html.erb
<% evil_string = "<script>alert('Gotcha');</script>" %>
<% good_string = "<strong>Welcome to my site!</strong>" %>

<%= evil_string %><br />
<%= good_string %><br />

app/views/demo/hello.html.erb
<h1>Hello world from hello</h1>

<%= 1 + 1 %>

<% target = 'world' %>

<%= "Hello #{target}" %>

<br/>

<% @array.each do |n| %>
  <%= n %><br/>
<% end %>

<%= link_to('Back to index', {:action => 'index'}) %><br/>

<br>

ID: <%= @id %>
ID: <%= params[:id] %>
Page: <%= @page %>
Next page: <%= @page.to_i + 1 %>

app/views/demo/index.html.erb
<h1>Hello world from index</h1>

<a href="/demo/hello">Hello page 1</a><br/>
<%= link_to('Hello page 2', {:action => 'hello'}) %><br/>

<%= link_to('Hello with parameters', {:action => 'hello', :page => 5, :id => 20}) %><br/>

<%= link_to('Roar', '#', :onclick => "jsRoar('Javascript'); return true;") %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Simple CMS: <%= @page_title || 'Admin Area' %></title>
  <%= stylesheet_link_tag('application', :media => 'all') %>
  <%= stylesheet_link_tag('admin', :media => 'all') %>
</head>
<body>
  <div id="header">
    <h1>Simple CMS Admin</h1>
  </div>

  <div id="main">
    <% if !flash[:notice].blank? %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <div id="content">
      <%= yield %>
    </div>
  </div>
  <div id="footer">
    <p id="copyright">&copy; prinzio.com</p>
   </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag('application', media: 'all') %>
    <%= javascript_include_tag('application') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<table summary="Page form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Subject Id</th>
    <td><%= f.text_field(:subject_id) %></td>
  </tr>
  <tr>
    <th>Permalink</th>
    <td><%= f.text_field(:permalink) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.text_field(:position) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
</table>

app/views/pages/delete.html.erb
<%= link_to('<< Back to List', pages_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Delete Page</h2>

  <%= form_for(@page, :method => 'delete') do |f| %>

    <p>Are you sure want to permanently delete this page?</p>
    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>
  <% end %>
</div>

app/views/pages/edit.html.erb
<%= link_to('<< Back to List', pages_path, :class => 'back-link') %>

<div class="pages new">
  <h2>Update Page</h2>

  <%= form_for(@page) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Page") %>
    </div>
  <% end %>
</div>

app/views/pages/index.html.erb
<div class="subjects index">
  <h2>Pages</h2>

  <%= link_to('Add New Page', new_page_path, :class => 'action new') %>

  <table class="listing" summary="Page list">
    <tr class="header">
      <th>#</th>
      <th>Name</th>
      <th>Subject Id</th>
      <th>Visible</th>
      <th>Permalink</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.name %></td>
      <td><%= page.subject_id %></td>
      <td class="center"><%= page.visible ? 'Yes' : 'No' %></td>
      <td class="center"><%= page.permalink %></td>
      <td class="actions">
        <%= link_to('Show', page_path(page), :class => 'action show') %>
        <%= link_to('Edit', edit_page_path(page), :class => 'action edit') %>
        <%= link_to('Delete', delete_page_path(page), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<%= link_to('<< Back to List', pages_path, :class => 'back-link') %>

<div class="pages new">
  <h2>Create Page</h2>

  <%= form_for(@page) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Page") %>
    </div>
  <% end %>
</div>

app/views/pages/show.html.erb
<%= link_to('<< Back to List', pages_path, :class => 'back-link') %>

<div class="page show">
  <h2>Show Page</h2>
  <table class="summary detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Subject Id</th>
      <td><%= @page.subject_id %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>
</div>

app/views/sections/_form.html.erb
<table summary="Section form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Page Id</th>
    <td><%= f.text_field(:page_id) %></td>
  </tr>
  <tr>
    <th>Content</th>
    <td><%= f.text_area(:content, :size => '40x10') %></td>
  </tr>
  <tr>
    <th>Content Type</th>
    <td>
      <%= f.radio_button(:content_type, 'text') %> Text
      <%= f.radio_button(:content_type, 'HTML') %> HTML
    </td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.text_field(:position) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
</table>

app/views/sections/delete.html.erb
<%= link_to('<< Back to List', sections_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Delete Section</h2>

  <%= form_for(@section, :method => 'delete') do |f| %>

    <p>Are you sure want to permanently delete this page?</p>
    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Section") %>
    </div>
  <% end %>
</div>

app/views/sections/edit.html.erb
<%= link_to('<< Back to List', sections_path, :class => 'back-link') %>

<div class="sections new">
  <h2>Update Section</h2>

  <%= form_for(@section) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Section") %>
    </div>
  <% end %>
</div>

app/views/sections/index.html.erb
<div class="sections index">
  <h2>Sections</h2>

  <%= link_to('Add New Section', new_section_path, :class => 'action new') %>

  <table class="listing" summary="Section list">
    <tr class="header">
      <th>#</th>
      <th>Name</th>
      <th>Page Id</th>
      <th>Visible</th>
      <th>Actions</th>
    </tr>
    <% @sections.each do |section| %>
    <tr>
      <td><%= section.position %></td>
      <td><%= section.name %></td>
      <td><%= section.page_id %></td>
      <td class="center"><%= section.visible ? 'Yes' : 'No' %></td>
      <td class="actions">
        <%= link_to('Show', section_path(section), :class => 'action show') %>
        <%= link_to('Edit', edit_section_path(section), :class => 'action edit') %>
        <%= link_to('Delete', delete_section_path(section), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>

</div>

app/views/sections/new.html.erb
<%= link_to('<< Back to List', sections_path, :class => 'back-link') %>

<div class="sections new">
  <h2>Create Section</h2>

  <%= form_for(@section) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    <div class="form-buttons">
      <%= f.submit("Create Section") %>
    </div>
  <% end %>
</div>

app/views/sections/show.html.erb
<%= link_to('<< Back to List', sections_path, :class => 'back-link') %>

<div class="section show">
  <h2>Show Section</h2>
  <table class="summary detail view">
    <tr>
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>
    <tr>
      <th>Page Id</th>
      <td><%= @section.page_id %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @section.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Content Type</th>
      <td><%= @section.content_type %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td><%= @section.content %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @section.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @section.updated_at %></td>
    </tr>
  </table>
</div>

app/views/subjects/_form.html.erb
<table summary="Subject form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.text_field(:position) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
</table>

app/views/subjects/delete.html.erb
<%= link_to('<< Back to List', subjects_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Delete Subject</h2>

  <%= form_for(@subject, :method => 'delete') do |f| %>

    <p>Are you sure want to permanently delete this subject?</p>
    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>
  <% end %>
</div>

app/views/subjects/edit.html.erb
<%= link_to('<< Back to List', subjects_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>
  <% end %>
</div>

app/views/subjects/index.html.erb
<div class="subjects index">
  <h2>Subjects</h2>

  <%= link_to('Add New Subject', new_subject_path, :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= status_tag(subject.visible) %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        <%= link_to('Show', subject_path(subject), :class => 'action show') %>
        <%= link_to('Edit', edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to('Delete', delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>

</div>

app/views/subjects/new.html.erb
<%= link_to('<< Back to List', subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>
  <% end %>
</div>

app/views/subjects/show.html.erb
<%= link_to('<< Back to List', subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>
  <table class="summary detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>
</div>